version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: line_provider_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  line-provider:
    build: ./line-provider
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres/line_provider_db
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - rabbitmq

  bet-maker:
    build: ./bet-maker
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres/bet_maker_db
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
