"""one migration

Revision ID: 9e71544cba19
Revises: 
Create Date: 2024-08-25 21:28:34.787550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import models


# revision identifiers, used by Alembic.
revision: str = '9e71544cba19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('state', models.bet.EventStateEnum('0', '1', '2'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_id'), 'bets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_id'), table_name='bets')
    op.drop_table('bets')
    # ### end Alembic commands ###
